<html>
  <body>
    <script>
      const fetchData = () => {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const success = true; // Simulate success or failure
            if (success) {
              resolve({ id: 1, name: "Alice" });
            } else {
              reject("Failed to fetch data");
            }
          }, 2000);
        });
      };

      // If you use await in function, you have to mark the function as async
      async function getData() {
        try {
          console.log("Fetching data...");

          const data = await fetchData(); // Waits until `fetchData` resolves, then the next statement will be executed
          console.log("Data received:", data);
        } catch (error) {
          console.log("Error:", error); // Catches any errors from `fetchData`
        }
      }

      // Async function without 'await'
      async function getDataWithoutAwait() {
        try {
          console.log("Fetching data without await...");
          const data = fetchData(); // fetchData is called but not awaited
          console.log(data); // Logs 'Promise { <pending> }' immediately
        } catch (err) {
          console.log("Error:", error);
        }
      }

      getData();      // Output after 2 seconds: "Data received: <data>"
      getDataWithoutAwait();    // Output immediately: "Promise { <pending> }" since the promise was not resolved before returning it
    </script>

    <script>
      // Chaining with await/async
      const fetchUser = () => {
        return new Promise((resolve) => {
          setTimeout(() => resolve({ id: 1, name: "Alice" }), 1000);
        });
      };

      const fetchOrders = (userId) => {
        return new Promise((resolve) => {
          console.log(userId);

          setTimeout(() => resolve(["Order1", "Order2"]), 1000);
        });
      };

      async function fetchUserData() {
        try {
          console.log("Fetching user..");
          const user = await fetchUser();
          console.log("User fetched:", user);
          console.log("Fetching order..");

          const orders = await fetchOrders(user.id);
          console.log("Orders fetched:", orders);
        } catch (error) {
          console.log("Error:", error);
        }
      }

      fetchUserData();
    </script>
  </body>
</html>
